//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;

    public partial class Product
    {


        private decimal _pricePerItem;

        private decimal _ourCostPerItem;

      [Key]  [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ItemID { get; set; }
        public string Description { get; set; }
        public decimal PricePerItem
        {
            get
            {
                return decimal.Round(_pricePerItem, 2);
            }
            set
            {
                _pricePerItem = decimal.Round(value, 2);
            }
        }

        public int QtyOnHand { get; set; }
        public decimal OurCostPerItem
        {
            get
            {
                return decimal.Round(_ourCostPerItem, 2);
            }
            set
            {
                _ourCostPerItem = decimal.Round(value, 2);
            }
        }
        public Nullable<System.DateTime> CreatedDate { get; set; }



    }
}
